from . import interactive_button
from . import interactive_list
from . import product_list
from . import provider_base
from . import whatsapp_history
from . import res_users
from . import channel_provider_line
from . import res_partner
from . import wa_template
from . import variables
from . import components
from . import mail_channel
from . import mail_message
from . import ir_http
from . import res_config_settings
from . import ir_attachment
from . import provider_meta
from . import ir_actions